# Generated by Django 2.0.6 on 2018-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_bal',
            name='Email',
        ),
    ]
