# Generated by Django 2.0.6 on 2018-07-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
