# Generated by Django 2.0.6 on 2018-07-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180703_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='Username',
        ),
    ]
