# Generated by Django 2.0.6 on 2018-07-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180703_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Fist_Name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Last_name',
            new_name='Last_Name',
        ),
    ]
